name: Rubocop

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v3.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
